### ISSUE TITLE
What is n_experiences?

### ISSUE THREAD

**Issue by hiteshvaidya** [AlbinSou/ocl_survey#8]
What is n_experiences in config/benchmarks/split_cifar100.yaml? 
If I want to run experiment on cifar-10 with 5 tasks each having 2 classes, wouldn't n_eperiences be 2 in that case? 
Also, get_results.py always has 20 set by default at various places. Shouldn't that be equal to 20?
If I create a new cifar-10 config file with n_experiences: 2, the experiement runs only for 1 task. Shouldn't it run untill 5 tasks?

**Comment by HamedHemati** [comment]
> What is n_experiences in config/benchmarks/split_cifar100.yaml?

The terms "task" and "experience" are often used interchangeably in the literature. Here,`n_experiences` denotes the number of tasks in the stream.
